name: React Native Tests

on:
  push:
    branches:
      - dev
      - staging
      - main
  pull_request:
    branches:
      - dev
      - staging
      - main

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      # Add Firebase emulator if needed for testing.
      firebase:
        image: firebase/emulators:latest
        ports:
          - 8080:8080
          - 9000:9000

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install Dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run Linter
      - name: Run ESLint
        run: npm run lint

      # Step 5: Run Unit Tests
      - name: Run Unit Tests
        run: npm test
        env:
          CI: true

      # Step 6: Run End-to-End Tests (Optional)
      - name: Install Detox CLI
        run: npm install -g detox-cli

      - name: Build and Test with Detox
        run: |
          detox build --configuration ios.sim.release
          detox test --configuration ios.sim.release
        env:
          CI: true

  build:
    name: Build React Native App
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install Dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the App
      - name: Build the app
        run: |
          npm run android:build
          npm run ios:build
